name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['master']

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo: latest
        ports:
          - 27017:27017

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
